id: P1403F411
initial_creation_type: ocr
source_metadata:
  volumes:
    33ab5f70dc5d4867a36ca848cbd5352e:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཡོན་ཏན་མཐའ་ཡས་པར་བསྟོད་པའི་འགྲེལ་པ།
      total_pages: 1539
      volume_number: 1
